config/routes.rb
Rails.application.routes.draw do
  root 'club#home'
  get '/privateclub', to: 'club#private'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :first_name, presence: true
  validates :last_name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sentitive: false}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/club_controller.rb
class ClubController < ApplicationController
    def home
      current_user
    end

    def private
      current_user
      redirect_to root_path, alert: 'Nice try! Please log in to enter the club' unless logged_in?
      @users = User.all
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user_path(user.id), success: 'You are now logged as #{@user.name}'
    else
      flash[:alert] =  'Sorry log in failed!'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path, notice: 'You are logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_param)
    if @user.save
      log_in @user
      flash[:success] = 'New user is successfully created and logged'
      redirect_to user_path(@user.id)
    else
      flash[:alert] = "Something went wrong: #{@user.errors.full_messages}"
      render :new
    end
  end

  def show
    current_user
    if logged_in?
      @user = User.find(params[:id])
    else
      redirect_to login_path, alert: "Sorry, you must login to access to this page"
    end
  end

  def edit
    current_user
    if logged_in? && current_user.id == params[:id].to_i
      @user = User.find(params[:id])
    elsif logged_in?
      redirect_to root_path, alert: "Sorry, you don't have access rights to this page"
    else
      redirect_to login_path, alert: "Sorry, you must login to access to this page"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_param)
      flash[:success] = 'User information successfully updated'
      redirect_to user_path(params[:id])
    else
      redirect_to edit_user_path(params[:id]), alert: "Something went wrong, information couldn't be updated: #{@user.errors.full_messages}"
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      log_out
      flash[:success] = 'User has been successfuly deleted'
      redirect_to root_path
    else
      flash[:alert] = "Something went wrong: #{@user.errors.full_messages}"
      render :show
    end
  end

  private

  def user_param
    params.require(:user).permit(:last_name, :first_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/club_helper.rb
module ClubHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !@current_user.nil?
  end

  def log_out
    session[:user_id] = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/club/home.html.erb
    <% if logged_in? %>
        <div class='jumbotron card text-center bg-dark text-warning'>
            <h1 class='text-uppercase font-weight-bold'>Welcome to your favorite private club <%= current_user.first_name %></h1>
            <hr class="star-light">
            <p class="text-faded mb-5">Can you feel it? It's PARTY TIME !</p>
            <p class='lead'>Join the <%= link_to 'PARTY', privateclub_path, class: 'btn btn-outline-warning btn-xl'%></p>
        </div>
    <% else %>
        <div class='jumbotron text-center bg-warning text-secondary'>
            <h1>Sorry, this is a private club!</h1>
            <p>You must <%= link_to 'log in', login_path %> to join the party</p>
            <p>If you are a new joiner, please <%= link_to 'create an account', new_user_path %> first</p>
        </div>
    <% end%>

app/views/club/private.html.erb
<div class='text-center'>
<img src="http://static1.squarespace.com/static/539caa50e4b04eb6983b1fc3/t/5aecb09b6d2a7340a0cd89de/1525461165705/rickdancey.gif?format=1000w" alt="party">
<div class='card-body border border-primary rounded m-2 p-3'>
  <h2 class="text-capitalize font-weight-bold text-dark">Party people</h2>
  <table class="table">
    <thead class="thead-dark">
      <tr>
      <th scope="col" class="text-info">#</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">email</th>
      <th scope="col">Member since</th>
      <th scope="col">Link</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <th scope="row" class="text-info"><%= user.id %></th>
        <td class="text-capitalize"><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td class='small'><%= user.created_at.strftime("%e %b %y - %H:%M:%S") %></td>
        <td><%= link_to 'Link', user_path(user.id), class: 'btn btn-success' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>

</div>

app/views/layouts/_header.html.erb
<div class='header'>
    <nav class='navbar bg-dark text-primary navbar-fixed-top navbar-expand-md justify-content-between'>
        <ul class="navbar-nav">
          <li class="nav-item"><a class="navbar-brand " href="<%= root_path %>">
          <img src="http://icons.iconarchive.com/icons/graphicloads/colorful-long-shadow/256/Home-icon.png" width="30" height="30" class="d-inline-block align-top" alt="">
          Home
        </a></li>
          <% if logged_in? %>
            <li class="nav-item"><%= link_to 'Club', privateclub_path, class: 'nav-link'%></li>
            <li class="nav-item"><%= link_to current_user.first_name + " " + current_user.last_name, user_path(current_user.id), class: 'nav-link'%></li>
        </ul>
        <ul class='navbar-nav navbar-right'>
            <li class="nav-item"><p class='navbar-brand'>Hi <%= current_user.first_name%>!</p></li>
            <li class="nav-item"><a href="<%= logout_path %>" class="nav-link" data-confirm="Are you sure?" data-method="DELETE"><img src="https://www.iconsdb.com/icons/preview/soylent-red/logout-xxl.png" width="25" height="25" class="d-inline-block align-top" alt="log out"></a></li>
          <% else %>
            <li class="nav-item"><%= link_to 'Log in', login_path, class: 'nav-link'%></li>
            <li class="nav-item"><%= link_to 'Register', new_user_path, class: 'nav-link'%></li>
          <% end %>
        </ul>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Club</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body class='body'>
    <%= render 'layouts/header', locals: {current_user: current_user}%>
      <% flash.each do |type, msg|%>
    <% case type %>
        <% when 'alert' %>
        <div class= "text-center text-light bg-danger rounded"> <%= content_tag :div, msg %> </div>
        <% when 'notice' %>
        <div class= "text-center text-dark bg-warning rounded"> <%= content_tag :div, msg %> </div>
        <% when 'success' %>
        <div class= "text-center text-light bg-success rounded"> <%= content_tag :div, msg %> </div>
    <% end %>
  <% end %>

      <%= yield %>

  </body>
</html>

app/views/users/edit.html.erb
<div class='container col-6 offset-3'>
  <div class='card'>
    <div class='card-header text-capitalize font-weight-bold bg-warning'>Edit Data for <%= @user.first_name %> <%= @user.last_name%> </div>
    <%= form_for @user do |f|%>
    <div class='card-body'>
      <div class='form-group'>
        <label for="first_name" class='col-form-label text-capitalize'>first name</label>
        <%= f.text_field 'first_name', class: 'form-control', id: 'first_name'%>
        <label for="last_name" class='col-form-label text-capitalize'>last name</label>
        <%= f.text_field 'last_name', class: 'form-control', id: 'last_name'%>
        <label for="email" class='col-form-label text-capitalize'>email</label>
        <%= f.text_field 'email', class: 'form-control', id: 'email'%>
        <%= f.submit 'Edit', class: 'btn btn-primary'%>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class='container col-6 offset-3'>
  <div class='card'>
    <div class='card-header text-capitalize font-weight-bold bg-info text-light'>Create a new user</div>
    <%= form_for @user do |f|%>
    <div class='card-body'>
      <div class='form-group'>
        <label for="first_name" class='col-form-label text-capitalize'>first name</label>
        <%= f.text_field 'first_name', class: 'form-control', id: 'first_name'%>
        <label for="last_name" class='col-form-label text-capitalize'>last name</label>
        <%= f.text_field 'last_name', class: 'form-control', id: 'last_name'%>
        <label for="email" class='col-form-label text-capitalize'>email</label>
        <%= f.text_field 'email', class: 'form-control', id: 'email'%>
        <label for="password" class='col-form-label text-capitalize'>password</label>
        <%= f.text_field 'password', class: 'form-control', type: 'password'%>
        <%= f.submit 'Sign Up', class: 'btn btn-primary'%>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container'>
  <div class='jumbotron text-center border border-warning bd-secondary'>
    <h1 class='display-4'>Welcome to <%= @user.first_name %>'s show page!</h1>
    <p class='lead'>Here are some personnal data about <%= @user.first_name %></p>
    <ul class='list-group col-4 offset-4'>
      <li class='list-group-item text-capitalize bg-dark text-light'> first name: <%= @user.first_name %></li>
      <li class='list-group-item text-capitalize bg-warning'> last name: <%= @user.last_name %></li>
      <li class='list-group-item bg-dark text-light'> email: <%= @user.email %></li>
    </ul>
    <% if current_user == @user %>
    <div class='p-3'>
      <%= link_to 'Edit', edit_user_path(@user.id), class: 'btn btn-primary' %>
      <%= link_to 'Delete', user_path(@user.id), class: 'btn btn-danger', 'data-confirm': "This profile will be deleted and you will be logged out", 'data-method': :delete %>
    </div>
    <% end %>
  </div>
</div>